#!/usr/bin/env python3

# dfrobot_ups.py


import smbus


addr = 0x10                                     # UPS i2c address
bus = smbus.SMBus(1)                            # device /dev/i2c-1

pid = bus.read_byte_data(addr, 0x01)            # product ID
version = bus.read_byte_data(addr, 0x02)        # firmware version

vcell = ((((bus.read_byte_data(addr,0x03) & 0xf) << 8)
          + bus.read_byte_data(addr, 0x04))
         * 1.25)

soc = (((bus.read_byte_data(addr,0x05) << 8) + bus.read_byte_data(addr, 0x06))
       / 256)


print("Product ID = 0x%x" % pid)
print("Firmware version = %d.%d" % (version >> 4, version & 0xf))
print("Battery voltage = %dmV" % vcell)
print("State of Charge = %.2f%%" % soc)
